### PR TITLE
Added API routes

### PR DESCRIPTION
**Pull request by nkootstra**
I modified the existing functionality and used [Eloquent Resources](https://laravel.com/docs/5.8/eloquent-resources) to simplify the output. I also added functionality to retrieve a specific event resource.

### CODE REVIEW

**Comment by imacrayon** [comment]
Awesome this looks great, thank you. I’ve got one more small request - could you add `created_at` & `update_at` to the JSON output. I think that would be useful for people who want to consume this data. Happy Hacktoberfest!

**Comment by nkootstra** [comment]
Sure. Will do later today :)

**Comment by nkootstra** [comment]
Done. Also rewrote some tests and added a Middleware to always return json instead of returning a 404. Same goes for when a model could not be found.

**Comment by imacrayon** [comment]
Thanks for all the work!

**Pull request merged**
